name: CI-CD

on: 
  push: 
    branches: ["main"]
    
jobs:
  CI:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: crclemente
          password: jrT86$_VtcJ!W_!
#          username: ${{secrets.DOCKERHUB_USER}}
#          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Construção da imagem Docker
        uses: actions/checkout@v3
      
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
#       uses: docker/build-push-action@v3.2.0
        with: 
          context: src
          file: \src\Dockerfile
          push: true
          tags: |
            crclemente/unyleya_devopsnapratica_ci_cd_unid4_atv4_carlos:${{github.run_number}}
            crclemente/unyleya_devopsnapratica_ci_cd_unid4_atv4_carlos:latest
#  CD:
#    runs-on: ubuntu-latest
#    needs: [CD]
#    steps: 
#      - uses: actions/checkout@v3.1.0
#      
#      - name: Definindo o context
#        uses: Azure/k8s-set-context@v3.0
#        with:
#          method: kubeconfig
#          kubeconfig: ${{secrets.K8S_CONFIG}}
          
    
